version: '3'
services:

  # postgresdb:
  #   image: 'postgres:13-alpine'
    
  #   ports:
  #     - 5432

  #   environment:
  #     # these are development credintials should use more secure
  #     # postgres image use those to create user and db
  #     - POSTGRES_USER=leon
  #     - POSTGRES_PASSWORD=a
  #     - POSTGRES_DB=leon

  #   volumes:
  #     - postgresdb:/var/lib/postgresql/data

  mysqldb:
   
    image: 'mysql:latest'    
    ports:
      - 3306
    

    environment:
      - MYSQL_DATABASE=leon
      - MYSQL_PASSWORD=leon
      - MYSQL_USER=leon
      - MYSQL_RANDOM_ROOT_PASSWORD=true

    volumes:
      - mysqldb:/var/lib/mysql


  redisdb:
    
    image: 'redis:alpine'
    
    ports:
      - 6379

  server:
    build: '.'
  
    ports: 
      - 3000:3000
  
    volumes:
      - .:/code
 
      
volumes:
   mysqldb:
